version: '3.8'
services:
    db:
        image: mysql:latest
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: 1028
            MYSQL_DATABASE: portfolio
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network

    backend:
        build: ./nest-app
        container_name: nest_backend
        ports:
            - '4000:4000'
        depends_on:
            - db
        networks:
            - app_network
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_USERNAME: root
            DB_PASSWORD: 1028
            DB_DATABASE: portfolio

    frontend:
        build: ./next-app
        container_name: next_frontend
        ports:
            - '3000:3000'
        depends_on:
            - backend
        networks:
            - app_network

volumes:
    db_data:

networks:
    app_network:
